/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Events */
        get: operations["list_audit_events_v1_admin_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_admin_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/auth/mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mfa Status */
        get: operations["mfa_status_v1_admin_auth_mfa_get"];
        put?: never;
        post?: never;
        /** Mfa Disable */
        delete: operations["mfa_disable_v1_admin_auth_mfa_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/auth/mfa/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mfa Enroll */
        post: operations["mfa_enroll_v1_admin_auth_mfa_enroll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/auth/mfa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mfa Setup */
        post: operations["mfa_setup_v1_admin_auth_mfa_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_v1_admin_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/kill-switches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Kill Switches */
        get: operations["get_kill_switches_v1_admin_kill_switches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/observability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Observability
         * @description T18: the one admin surface for "is the pipeline healthy and what is
         *     it costing" — ingestion health, job queue state, and AI spend vs.
         *     budget, all scoped to what an editor needs to see in the last 24h.
         */
        get: operations["get_observability_v1_admin_observability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review Queue */
        get: operations["get_review_queue_v1_admin_review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_v1_admin_sources_get"];
        put?: never;
        /**
         * Create Source
         * @description Create a source. With no rights fields it starts DISABLED/inactive. A
         *     preset flow may also pass rights fields to enable + activate in one call;
         *     that goes through the same ADR-002 gate as PATCH (ADMIN only, evidence URL
         *     and reviewer required) — a human still supplies the evidence.
         */
        post: operations["create_source_v1_admin_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/sources/test-feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Feed
         * @description Preview a candidate feed URL (read-only; nothing is saved).
         */
        post: operations["test_feed_v1_admin_sources_test_feed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Source */
        patch: operations["update_source_v1_admin_sources__source_id__patch"];
        trace?: never;
    };
    "/v1/admin/sources/{source_id}/x-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create X Account */
        post: operations["create_x_account_v1_admin_sources__source_id__x_account_post"];
        delete?: never;
        options?: never;
        head?: never;
        /** Update X Account */
        patch: operations["update_x_account_v1_admin_sources__source_id__x_account_patch"];
        trace?: never;
    };
    "/v1/admin/stories/{story_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Story Detail */
        get: operations["get_story_detail_v1_admin_stories__story_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/stories/{story_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Story */
        post: operations["approve_story_v1_admin_stories__story_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/stories/{story_id}/approve-breaking-alert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Breaking Alert
         * @description T17: the "never auto-sent" gate for a `BREAKING_ALERT` push — separate
         *     from, and in addition to, the publish approval NON_NEGOTIABLES #5
         *     already required for a `sensitivity == 'BREAKING'` story to reach
         *     PUBLISHED. `notification_dispatch` (app/jobs/notify.py) only ever
         *     considers a story for a breaking push once `breaking_alert_approved_at`
         *     is set here.
         */
        post: operations["approve_breaking_alert_v1_admin_stories__story_id__approve_breaking_alert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/stories/{story_id}/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Correct Story */
        post: operations["correct_story_v1_admin_stories__story_id__correct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/stories/{story_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Story */
        post: operations["reject_story_v1_admin_stories__story_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/stories/{story_id}/retract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retract Story */
        post: operations["retract_story_v1_admin_stories__story_id__retract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/stories/{story_id}/variants/{language}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Write Story Draft
         * @description Editor-written draft for a story still in review: the fallback when no
         *     AI route may draft it (NO_PAID_PROVIDER, budget exhausted, outage).
         *     Published stories go through /correct instead, which records a
         *     Correction. English stays canonical (NON_NEGOTIABLES #7): Telugu needs an
         *     English variant to derive from, must pass the same QA as machine
         *     translation, and is invalidated whenever the English is rewritten.
         */
        put: operations["write_story_draft_v1_admin_stories__story_id__variants__language__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/x-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List X Accounts */
        get: operations["list_x_accounts_v1_admin_x_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Track Event
         * @description T17 §9.4 client-emitted events (`story_share`, `notification_received`,
         *     `notification_open`) — the ones the server can't observe on its own
         *     (a user tapping share, or a device receiving/opening a push). No auth:
         *     browsing/sharing works without login (NON_NEGOTIABLES #9), and there's
         *     no per-user data here beyond whatever the caller puts in `properties`.
         */
        post: operations["track_event_v1_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Home */
        get: operations["get_home_v1_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Account */
        delete: operations["delete_account_v1_me_account_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_v1_me_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Preferences */
        patch: operations["update_preferences_v1_me_preferences_patch"];
        trace?: never;
    };
    "/v1/me/push-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Push Token */
        post: operations["register_push_token_v1_me_push_tokens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/saved/{story_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Story */
        post: operations["save_story_v1_me_saved__story_id__post"];
        /** Unsave Story */
        delete: operations["unsave_story_v1_me_saved__story_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stories */
        get: operations["list_stories_v1_stories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stories/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Story */
        get: operations["get_story_v1_stories__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stories/{slug}/share-meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Story Share Meta */
        get: operations["get_story_share_meta_v1_stories__slug__share_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/topics/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Topic */
        get: operations["get_topic_v1_topics__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminActionRequest */
        AdminActionRequest: {
            /** Reason */
            reason?: string | null;
        };
        /** AdminActionResponse */
        AdminActionResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "DRAFT" | "AI_READY" | "REVIEW_REQUIRED" | "APPROVED" | "SCHEDULED" | "PUBLISHED" | "UPDATED" | "RETRACTED" | "CORRECTION_PENDING" | "ARCHIVED";
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
        };
        /** AdminAuditEventOut */
        AdminAuditEventOut: {
            /** Action */
            action: string;
            /** Actor */
            actor?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** AdminCorrectionOut */
        AdminCorrectionOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** New Text Hash */
            new_text_hash: string;
            /** Old Text Hash */
            old_text_hash: string;
            /** Reason */
            reason: string;
        };
        /** AdminCorrectionRequest */
        AdminCorrectionRequest: {
            /** Headline */
            headline?: string | null;
            /** Reason */
            reason: string;
            /** Summary */
            summary?: string | null;
            /** Why Matters */
            why_matters?: string | null;
        };
        /**
         * AdminDraftRequest
         * @description An editor-written story variant for a story still in review — the
         *     fallback when no AI route may draft it (e.g. NO_PAID_PROVIDER).
         */
        AdminDraftRequest: {
            /** Headline */
            headline: string;
            /** Reason */
            reason?: string | null;
            /** Summary */
            summary: string;
            /** Why Matters */
            why_matters?: string | null;
        };
        /** AdminFeedTestOut */
        AdminFeedTestOut: {
            /** Error */
            error: string | null;
            /** Headlines */
            headlines: string[];
            /** Item Count */
            item_count: number;
            /** Ok */
            ok: boolean;
        };
        /** AdminFeedTestRequest */
        AdminFeedTestRequest: {
            /** Feed Url */
            feed_url: string;
        };
        /** AdminJobOut */
        AdminJobOut: {
            /** Attempts */
            attempts: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Error */
            last_error?: string | null;
            /** Locked At */
            locked_at?: string | null;
            /**
             * Run After
             * Format: date-time
             */
            run_after: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "RUNNING" | "DONE" | "FAILED";
            /** Type */
            type: string;
        };
        /** AdminLoginRequest */
        AdminLoginRequest: {
            /** Email */
            email: string;
            /** Mfa Code */
            mfa_code?: string | null;
            /** Password */
            password: string;
        };
        /** AdminLoginResponse */
        AdminLoginResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /**
             * Mfa Enrollment Required
             * @default false
             */
            mfa_enrollment_required: boolean;
            /**
             * Role
             * @enum {string}
             */
            role: "EDITOR" | "ADMIN";
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /** AdminRejectRequest */
        AdminRejectRequest: {
            /**
             * Archive
             * @default false
             */
            archive: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** AdminSourceCreate */
        AdminSourceCreate: {
            /** Active */
            active?: boolean | null;
            /** Base Url */
            base_url?: string | null;
            /** Category */
            category?: string | null;
            /** Country */
            country?: string | null;
            /** Feed Url */
            feed_url?: string | null;
            /** Language */
            language?: string | null;
            /** Name */
            name: string;
            /** Refresh Minutes */
            refresh_minutes?: number | null;
            /** Reviewer */
            reviewer?: string | null;
            rights_evidence?: components["schemas"]["RightsEvidence"] | null;
            /** Rights Evidence Url */
            rights_evidence_url?: string | null;
            /** Rights Reviewed At */
            rights_reviewed_at?: string | null;
            /** Rights Status */
            rights_status?: ("DISABLED" | "LINK_ONLY" | "LICENSED_METADATA" | "LICENSED_REPURPOSE") | null;
            /** Source Type */
            source_type?: string | null;
        };
        /** AdminSourceOut */
        AdminSourceOut: {
            /** Active */
            active: boolean;
            /** Base Url */
            base_url?: string | null;
            /** Category */
            category?: string | null;
            /** Country */
            country?: string | null;
            /** Fail Count */
            fail_count: number;
            /** Feed Url */
            feed_url?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Language */
            language?: string | null;
            /** Last Error At */
            last_error_at?: string | null;
            /** Last Success At */
            last_success_at?: string | null;
            /** Name */
            name: string;
            /** Refresh Minutes */
            refresh_minutes?: number | null;
            /** Reviewer */
            reviewer?: string | null;
            rights_evidence?: components["schemas"]["RightsEvidence"];
            /** Rights Evidence Url */
            rights_evidence_url?: string | null;
            /** Rights Reviewed At */
            rights_reviewed_at?: string | null;
            /**
             * Rights Status
             * @enum {string}
             */
            rights_status: "DISABLED" | "LINK_ONLY" | "LICENSED_METADATA" | "LICENSED_REPURPOSE";
            /** Source Type */
            source_type?: string | null;
        };
        /** AdminSourceUpdate */
        AdminSourceUpdate: {
            /** Active */
            active?: boolean | null;
            /** Base Url */
            base_url?: string | null;
            /** Category */
            category?: string | null;
            /** Country */
            country?: string | null;
            /** Feed Url */
            feed_url?: string | null;
            /** Language */
            language?: string | null;
            /** Name */
            name?: string | null;
            /** Refresh Minutes */
            refresh_minutes?: number | null;
            /** Reviewer */
            reviewer?: string | null;
            rights_evidence?: components["schemas"]["RightsEvidence"] | null;
            /** Rights Evidence Url */
            rights_evidence_url?: string | null;
            /** Rights Reviewed At */
            rights_reviewed_at?: string | null;
            /** Rights Status */
            rights_status?: ("DISABLED" | "LINK_ONLY" | "LICENSED_METADATA" | "LICENSED_REPURPOSE") | null;
            /** Source Type */
            source_type?: string | null;
        };
        /**
         * AdminStoryDetailOut
         * @description The §9.3/§15 review-screen payload: source + rights state, original
         *     metadata, the AI draft, sensitivity, and correction/audit history side
         *     by side.
         */
        AdminStoryDetailOut: {
            /** Canonical Slug */
            canonical_slug: string;
            /** Corrections */
            corrections?: components["schemas"]["AdminCorrectionOut"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Importance */
            importance: number;
            /** Published At */
            published_at?: string | null;
            review_task?: components["schemas"]["ReviewQueueItemOut"] | null;
            /**
             * Sensitivity
             * @enum {string}
             */
            sensitivity: "NONE" | "IMMIGRATION" | "LEGAL" | "FINANCIAL" | "BREAKING" | "OBITUARY_ACCUSATION";
            /** Sources */
            sources?: components["schemas"]["AdminStorySourceOut"][];
            /**
             * Status
             * @enum {string}
             */
            status: "DRAFT" | "AI_READY" | "REVIEW_REQUIRED" | "APPROVED" | "SCHEDULED" | "PUBLISHED" | "UPDATED" | "RETRACTED" | "CORRECTION_PENDING" | "ARCHIVED";
            /** Variants */
            variants?: {
                [key: string]: components["schemas"]["StoryVariantOut"];
            };
        };
        /** AdminStorySourceOut */
        AdminStorySourceOut: {
            /** Published At */
            published_at?: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "PRIMARY" | "SUPPORTING";
            /** Source Name */
            source_name: string;
            /**
             * Source Rights Status
             * @enum {string}
             */
            source_rights_status: "DISABLED" | "LINK_ONLY" | "LICENSED_METADATA" | "LICENSED_REPURPOSE";
            /** Title */
            title?: string | null;
            /** Url */
            url: string;
        };
        /** AdminXAccountCreate */
        AdminXAccountCreate: {
            /** Budget Class */
            budget_class?: string | null;
            /** Handle */
            handle: string;
            /** Polling Cadence */
            polling_cadence?: number | null;
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /** X User Id */
            x_user_id: string;
        };
        /** AdminXAccountOut */
        AdminXAccountOut: {
            /** Active */
            active: boolean;
            /** Budget Class */
            budget_class?: string | null;
            /** Budget Paused */
            budget_paused: boolean;
            /** Circuit Breaker Tripped */
            circuit_breaker_tripped: boolean;
            /** Fail Count */
            fail_count: number;
            /** Handle */
            handle: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Error At */
            last_error_at?: string | null;
            /** Last Success At */
            last_success_at?: string | null;
            /** Month To Date Cost Usd */
            month_to_date_cost_usd: number;
            /** Polling Cadence */
            polling_cadence?: number | null;
            /** Priority */
            priority: number;
            /** Recent Error Count 24H */
            recent_error_count_24h: number;
            /**
             * Rights Status
             * @enum {string}
             */
            rights_status: "DISABLED" | "LINK_ONLY" | "LICENSED_METADATA" | "LICENSED_REPURPOSE";
            /** Since Id */
            since_id?: string | null;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** X User Id */
            x_user_id: string;
        };
        /** AdminXAccountUpdate */
        AdminXAccountUpdate: {
            /** Budget Class */
            budget_class?: string | null;
            /** Handle */
            handle?: string | null;
            /** Polling Cadence */
            polling_cadence?: number | null;
            /** Priority */
            priority?: number | null;
            /** Since Id */
            since_id?: string | null;
        };
        /** AiCostRowOut */
        AiCostRowOut: {
            /** Cost Usd */
            cost_usd: number;
            /** Day */
            day: string;
            /** Task */
            task: string;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
        };
        /** AiCostSummaryOut */
        AiCostSummaryOut: {
            /** Daily Alert Usd */
            daily_alert_usd?: number | null;
            /** Month To Date Cost Usd */
            month_to_date_cost_usd: number;
            /** Monthly Budget Remaining Usd */
            monthly_budget_remaining_usd?: number | null;
            /** Monthly Budget Usd */
            monthly_budget_usd?: number | null;
            /** Over Monthly Budget */
            over_monthly_budget: boolean;
            /** Rows */
            rows: components["schemas"]["AiCostRowOut"][];
            /** Today Cost Usd */
            today_cost_usd: number;
        };
        /** AnalyticsEventIn */
        AnalyticsEventIn: {
            /**
             * Event
             * @enum {string}
             */
            event: "app_open" | "feed_view" | "story_open" | "story_save" | "story_share" | "language_switch" | "search" | "notification_open" | "notification_opt_in" | "onboarding_complete" | "account_delete_request" | "report_issue" | "notification_received";
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
        };
        /** AnalyticsEventResponse */
        AnalyticsEventResponse: {
            /**
             * Accepted
             * @default true
             */
            accepted: boolean;
        };
        /** ConfigResponse */
        ConfigResponse: {
            /** Features */
            features?: {
                [key: string]: boolean;
            };
            /** Languages */
            languages?: ("en" | "te")[];
            /** Topics */
            topics?: components["schemas"]["TopicOut"][];
        };
        /** DeleteAccountResponse */
        DeleteAccountResponse: {
            /** Deleted */
            deleted: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HomeResponse */
        HomeResponse: {
            /** Top Stories */
            top_stories?: components["schemas"]["StoryOut"][];
            /** Topics */
            topics?: components["schemas"]["TopicOut"][];
        };
        /** JobQueueHealthOut */
        JobQueueHealthOut: {
            /** Counts By Status */
            counts_by_status: {
                [key: string]: number;
            };
            /** Oldest Pending Age Seconds */
            oldest_pending_age_seconds?: number | null;
        };
        /**
         * KillSwitchesOut
         * @description Read-only view of the §15 global kill switches (env-backed; no
         *     publish logic exists to gate yet — see T12).
         */
        KillSwitchesOut: {
            /** Auto Publish Category Immigration */
            auto_publish_category_immigration: boolean;
            /** Auto Publish Global */
            auto_publish_global: boolean;
        };
        /** MeResponse */
        MeResponse: {
            /** Email */
            email?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            profile: components["schemas"]["ProfileOut"];
            /** Saved Story Ids */
            saved_story_ids?: string[];
        };
        /** MfaDisableRequest */
        MfaDisableRequest: {
            /** Code */
            code: string;
        };
        /** MfaEnrollRequest */
        MfaEnrollRequest: {
            /** Code */
            code: string;
            /** Secret */
            secret: string;
        };
        /** MfaSetupResponse */
        MfaSetupResponse: {
            /** Otpauth Url */
            otpauth_url: string;
            /** Secret */
            secret: string;
        };
        /** MfaStatusResponse */
        MfaStatusResponse: {
            /** Enabled */
            enabled: boolean;
        };
        /**
         * NotificationOut
         * @description §9.4 notification history — deep link is `story_id` (None means the
         *     home feed, e.g. DAILY_BRIEFING or a suppressed/retracted target).
         */
        NotificationOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sent At */
            sent_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "SENT" | "FAILED" | "SUPPRESSED";
            /** Story Id */
            story_id: string | null;
            /** Suppressed Reason */
            suppressed_reason?: ("QUIET_HOURS" | "DAILY_CAP") | null;
            /**
             * Type
             * @enum {string}
             */
            type: "DAILY_BRIEFING" | "TOPIC_ALERT" | "BREAKING_ALERT";
        };
        /** ObservabilityOut */
        ObservabilityOut: {
            ai_cost: components["schemas"]["AiCostSummaryOut"];
            /** Ingestion Health */
            ingestion_health: components["schemas"]["SourceIngestionHealthOut"][];
            job_queue: components["schemas"]["JobQueueHealthOut"];
            x_cost: components["schemas"]["XCostSummaryOut"];
        };
        /**
         * PersonalizationOut
         * @description §8.4 explainability: present only when the request supplied
         *     preferences to rank against, and only ever built from signals that
         *     actually matched (T16/ADR-005).
         */
        PersonalizationOut: {
            /** Explanation */
            explanation?: string | null;
            /** Score */
            score: number;
            /** Why Matters */
            why_matters?: string | null;
        };
        /** PreferencesUpdate */
        PreferencesUpdate: {
            /** Breaking Alerts Enabled */
            breaking_alerts_enabled?: boolean | null;
            /** Daily Briefing Enabled */
            daily_briefing_enabled?: boolean | null;
            /** Home City */
            home_city?: string | null;
            /** Home State */
            home_state?: string | null;
            /** Language */
            language?: ("en" | "te") | null;
            /** Max Alerts Per Day */
            max_alerts_per_day?: number | null;
            /** Notification Mode */
            notification_mode?: string | null;
            /** Quiet Hours End */
            quiet_hours_end?: number | null;
            /** Quiet Hours Start */
            quiet_hours_start?: number | null;
            /** Residence Country */
            residence_country?: string | null;
            /** Residence Region */
            residence_region?: string | null;
            /** Topic Slugs */
            topic_slugs?: string[] | null;
        };
        /** ProfileOut */
        ProfileOut: {
            /**
             * Breaking Alerts Enabled
             * @default true
             */
            breaking_alerts_enabled: boolean;
            /**
             * Daily Briefing Enabled
             * @default true
             */
            daily_briefing_enabled: boolean;
            /** Home City */
            home_city?: string | null;
            /** Home State */
            home_state?: string | null;
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "te";
            /**
             * Max Alerts Per Day
             * @default 5
             */
            max_alerts_per_day: number;
            /** Notification Mode */
            notification_mode?: string | null;
            /** Quiet Hours End */
            quiet_hours_end?: number | null;
            /** Quiet Hours Start */
            quiet_hours_start?: number | null;
            /** Residence Country */
            residence_country?: string | null;
            /** Residence Region */
            residence_region?: string | null;
            /** Topics */
            topics?: components["schemas"]["TopicOut"][];
        };
        /** PushTokenCreate */
        PushTokenCreate: {
            /**
             * Platform
             * @enum {string}
             */
            platform: "ios" | "android" | "web";
            /** Token */
            token: string;
        };
        /** PushTokenResponse */
        PushTokenResponse: {
            /** Registered */
            registered: boolean;
        };
        /** ReviewQueueItemOut */
        ReviewQueueItemOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decision */
            decision?: string | null;
            /** Headline */
            headline?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason: string;
            /** Source Names */
            source_names?: string[];
            /** Source Title */
            source_title?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "IN_REVIEW" | "APPROVED" | "REJECTED";
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
        };
        /**
         * RightsEvidence
         * @description §5.1 evidence record beyond the first-class rights_evidence_url/
         *     rights_reviewed_at/reviewer columns on `AdminSourceOut`.
         */
        RightsEvidence: {
            /** Expires At */
            expires_at?: string | null;
            /** Notes */
            notes?: string | null;
            /** Permitted Fields */
            permitted_fields?: string[];
            /** Restrictions */
            restrictions?: string | null;
            /** Terms Url */
            terms_url?: string | null;
            /** Territory */
            territory?: string | null;
        };
        /** SavedStoryResponse */
        SavedStoryResponse: {
            /** Saved */
            saved: boolean;
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Items */
            items?: components["schemas"]["StoryOut"][];
            /** Query */
            query: string;
        };
        /** ShareMetaResponse */
        ShareMetaResponse: {
            /** Canonical Url */
            canonical_url: string;
            /** Description */
            description: string;
            /** Image Url */
            image_url?: string | null;
            /** Title */
            title: string;
        };
        /**
         * SourceIngestionHealthOut
         * @description T18 §9.3 "ingestion health": one row per source, scoped to the
         *     `source_fetch` jobs run in the last 24h (not all-time counters, which
         *     `fail_count`/`AdminSourceOut` already expose).
         */
        SourceIngestionHealthOut: {
            /** Circuit Breaker Tripped */
            circuit_breaker_tripped: boolean;
            /** Fail Count */
            fail_count: number;
            /** Failure Count 24H */
            failure_count_24h: number;
            /** Last Error At */
            last_error_at?: string | null;
            /** Last Success At */
            last_success_at?: string | null;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Source Name */
            source_name: string;
            /** Success Count 24H */
            success_count_24h: number;
        };
        /** StoriesListResponse */
        StoriesListResponse: {
            /** Items */
            items: components["schemas"]["StoryOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * StoryOut
         * @description Appendix A's sample content object, shaped for API consumption.
         */
        StoryOut: {
            /** Canonical Slug */
            canonical_slug: string;
            /** Countries */
            countries?: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Importance */
            importance: number;
            personalization?: components["schemas"]["PersonalizationOut"] | null;
            /** Published At */
            published_at?: string | null;
            /**
             * Sensitivity
             * @enum {string}
             */
            sensitivity: "NONE" | "IMMIGRATION" | "LEGAL" | "FINANCIAL" | "BREAKING" | "OBITUARY_ACCUSATION";
            /** Sources */
            sources?: components["schemas"]["StorySourceOut"][];
            /**
             * Status
             * @enum {string}
             */
            status: "DRAFT" | "AI_READY" | "REVIEW_REQUIRED" | "APPROVED" | "SCHEDULED" | "PUBLISHED" | "UPDATED" | "RETRACTED" | "CORRECTION_PENDING" | "ARCHIVED";
            /** Topics */
            topics?: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Variants */
            variants?: {
                [key: string]: components["schemas"]["StoryVariantOut"];
            };
        };
        /** StorySourceOut */
        StorySourceOut: {
            /** Published At */
            published_at?: string | null;
            /** Title */
            title?: string | null;
            /** Url */
            url: string;
        };
        /** StoryVariantOut */
        StoryVariantOut: {
            /** Headline */
            headline: string;
            /**
             * Language
             * @enum {string}
             */
            language: "en" | "te";
            /**
             * Qa Status
             * @default PENDING
             * @enum {string}
             */
            qa_status: "PENDING" | "PASSED" | "FAILED";
            /** Summary */
            summary: string;
            /** Why Matters */
            why_matters?: string | null;
        };
        /** TopicDetailResponse */
        TopicDetailResponse: {
            /** Next Cursor */
            next_cursor?: string | null;
            /** Stories */
            stories?: components["schemas"]["StoryOut"][];
            topic: components["schemas"]["TopicOut"];
        };
        /** TopicOut */
        TopicOut: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * XCostSummaryOut
         * @description X4 §19: same shape as `AiCostSummaryOut` but scoped to X API spend,
         *     plus how many low-priority accounts the budget guard is currently
         *     pausing as a result.
         */
        XCostSummaryOut: {
            /** Low Priority Accounts Paused */
            low_priority_accounts_paused: number;
            /** Month To Date Cost Usd */
            month_to_date_cost_usd: number;
            /** Monthly Budget Remaining Usd */
            monthly_budget_remaining_usd?: number | null;
            /** Monthly Budget Usd */
            monthly_budget_usd?: number | null;
            /** Over Monthly Budget */
            over_monthly_budget: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_audit_events_v1_admin_audit_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuditEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_admin_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mfa_status_v1_admin_auth_mfa_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mfa_disable_v1_admin_auth_mfa_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaDisableRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mfa_enroll_v1_admin_auth_mfa_enroll_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaEnrollRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mfa_setup_v1_admin_auth_mfa_setup_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaSetupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_v1_admin_jobs_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kill_switches_v1_admin_kill_switches_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KillSwitchesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_observability_v1_admin_observability_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservabilityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_queue_v1_admin_review_queue_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueueItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_v1_admin_sources_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSourceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_source_v1_admin_sources_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_feed_v1_admin_sources_test_feed_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminFeedTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminFeedTestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_source_v1_admin_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSourceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_x_account_v1_admin_sources__source_id__x_account_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminXAccountCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminXAccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_x_account_v1_admin_sources__source_id__x_account_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminXAccountUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminXAccountOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_story_detail_v1_admin_stories__story_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStoryDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_story_v1_admin_stories__story_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_breaking_alert_v1_admin_stories__story_id__approve_breaking_alert_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_story_v1_admin_stories__story_id__correct_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_story_v1_admin_stories__story_id__reject_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminRejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retract_story_v1_admin_stories__story_id__retract_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_story_draft_v1_admin_stories__story_id__variants__language__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                story_id: string;
                language: "en" | "te";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_x_accounts_v1_admin_x_accounts_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminXAccountOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    track_event_v1_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyticsEventIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_home_v1_home_get: {
        parameters: {
            query?: {
                residence_country?: string | null;
                residence_region?: string | null;
                home_state?: string | null;
                home_city?: string | null;
                topics?: string | null;
                segment?: "general" | "international_student" | "graduate_opt" | "professional" | "family_parent" | "other";
                student_briefing?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_v1_me_account_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteAccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_v1_me_notifications_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_preferences_v1_me_preferences_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_push_token_v1_me_push_tokens_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushTokenCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_story_v1_me_saved__story_id__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedStoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsave_story_v1_me_saved__story_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedStoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_v1_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stories_v1_stories_get: {
        parameters: {
            query?: {
                topic?: string | null;
                country?: string | null;
                limit?: number;
                cursor?: string | null;
                ids?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoriesListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_story_v1_stories__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_story_share_meta_v1_stories__slug__share_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareMetaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topic_v1_topics__slug__get: {
        parameters: {
            query?: {
                cursor?: string | null;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
