/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Events */
        get: operations["list_audit_events_v1_admin_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_admin_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_v1_admin_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/kill-switches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Kill Switches */
        get: operations["get_kill_switches_v1_admin_kill_switches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review Queue */
        get: operations["get_review_queue_v1_admin_review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_v1_admin_sources_get"];
        put?: never;
        /** Create Source */
        post: operations["create_source_v1_admin_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Source */
        patch: operations["update_source_v1_admin_sources__source_id__patch"];
        trace?: never;
    };
    "/v1/admin/stories/{story_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Story */
        post: operations["approve_story_v1_admin_stories__story_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/stories/{story_id}/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Correct Story */
        post: operations["correct_story_v1_admin_stories__story_id__correct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/stories/{story_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Story */
        post: operations["reject_story_v1_admin_stories__story_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/stories/{story_id}/retract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retract Story */
        post: operations["retract_story_v1_admin_stories__story_id__retract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Home */
        get: operations["get_home_v1_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Account */
        delete: operations["delete_account_v1_me_account_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Preferences */
        patch: operations["update_preferences_v1_me_preferences_patch"];
        trace?: never;
    };
    "/v1/me/push-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Push Token */
        post: operations["register_push_token_v1_me_push_tokens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/saved/{story_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Story */
        post: operations["save_story_v1_me_saved__story_id__post"];
        /** Unsave Story */
        delete: operations["unsave_story_v1_me_saved__story_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stories */
        get: operations["list_stories_v1_stories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stories/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Story */
        get: operations["get_story_v1_stories__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stories/{slug}/share-meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Story Share Meta */
        get: operations["get_story_share_meta_v1_stories__slug__share_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/topics/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Topic */
        get: operations["get_topic_v1_topics__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminActionRequest */
        AdminActionRequest: {
            /** Reason */
            reason?: string | null;
        };
        /** AdminActionResponse */
        AdminActionResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "DRAFT" | "AI_READY" | "REVIEW_REQUIRED" | "APPROVED" | "SCHEDULED" | "PUBLISHED" | "UPDATED" | "RETRACTED" | "CORRECTION_PENDING";
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
        };
        /** AdminAuditEventOut */
        AdminAuditEventOut: {
            /** Action */
            action: string;
            /** Actor */
            actor?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** AdminJobOut */
        AdminJobOut: {
            /** Attempts */
            attempts: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Error */
            last_error?: string | null;
            /** Locked At */
            locked_at?: string | null;
            /**
             * Run After
             * Format: date-time
             */
            run_after: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "RUNNING" | "DONE" | "FAILED";
            /** Type */
            type: string;
        };
        /** AdminLoginRequest */
        AdminLoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** AdminLoginResponse */
        AdminLoginResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /**
             * Role
             * @enum {string}
             */
            role: "EDITOR" | "ADMIN";
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /** AdminSourceCreate */
        AdminSourceCreate: {
            /** Base Url */
            base_url?: string | null;
            /** Country */
            country?: string | null;
            /** Feed Url */
            feed_url?: string | null;
            /** Language */
            language?: string | null;
            /** Name */
            name: string;
            /** Refresh Minutes */
            refresh_minutes?: number | null;
            /** Source Type */
            source_type?: string | null;
        };
        /** AdminSourceOut */
        AdminSourceOut: {
            /** Active */
            active: boolean;
            /** Base Url */
            base_url?: string | null;
            /** Country */
            country?: string | null;
            /** Fail Count */
            fail_count: number;
            /** Feed Url */
            feed_url?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Language */
            language?: string | null;
            /** Last Error At */
            last_error_at?: string | null;
            /** Last Success At */
            last_success_at?: string | null;
            /** Name */
            name: string;
            /** Refresh Minutes */
            refresh_minutes?: number | null;
            /** Reviewer */
            reviewer?: string | null;
            rights_evidence?: components["schemas"]["RightsEvidence"];
            /** Rights Evidence Url */
            rights_evidence_url?: string | null;
            /** Rights Reviewed At */
            rights_reviewed_at?: string | null;
            /**
             * Rights Status
             * @enum {string}
             */
            rights_status: "DISABLED" | "LINK_ONLY" | "LICENSED_METADATA" | "LICENSED_REPURPOSE";
            /** Source Type */
            source_type?: string | null;
        };
        /** AdminSourceUpdate */
        AdminSourceUpdate: {
            /** Active */
            active?: boolean | null;
            /** Base Url */
            base_url?: string | null;
            /** Country */
            country?: string | null;
            /** Feed Url */
            feed_url?: string | null;
            /** Language */
            language?: string | null;
            /** Name */
            name?: string | null;
            /** Refresh Minutes */
            refresh_minutes?: number | null;
            /** Reviewer */
            reviewer?: string | null;
            rights_evidence?: components["schemas"]["RightsEvidence"] | null;
            /** Rights Evidence Url */
            rights_evidence_url?: string | null;
            /** Rights Reviewed At */
            rights_reviewed_at?: string | null;
            /** Rights Status */
            rights_status?: ("DISABLED" | "LINK_ONLY" | "LICENSED_METADATA" | "LICENSED_REPURPOSE") | null;
            /** Source Type */
            source_type?: string | null;
        };
        /** ConfigResponse */
        ConfigResponse: {
            /** Features */
            features?: {
                [key: string]: boolean;
            };
            /** Languages */
            languages?: ("en" | "te")[];
            /** Topics */
            topics?: components["schemas"]["TopicOut"][];
        };
        /** DeleteAccountResponse */
        DeleteAccountResponse: {
            /** Deleted */
            deleted: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HomeResponse */
        HomeResponse: {
            /** Top Stories */
            top_stories?: components["schemas"]["StoryOut"][];
            /** Topics */
            topics?: components["schemas"]["TopicOut"][];
        };
        /**
         * KillSwitchesOut
         * @description Read-only view of the §15 global kill switches (env-backed; no
         *     publish logic exists to gate yet — see T12).
         */
        KillSwitchesOut: {
            /** Auto Publish Category Immigration */
            auto_publish_category_immigration: boolean;
            /** Auto Publish Global */
            auto_publish_global: boolean;
        };
        /** MeResponse */
        MeResponse: {
            /** Email */
            email?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            profile: components["schemas"]["ProfileOut"];
            /** Saved Story Ids */
            saved_story_ids?: string[];
        };
        /** PreferencesUpdate */
        PreferencesUpdate: {
            /** Home City */
            home_city?: string | null;
            /** Home State */
            home_state?: string | null;
            /** Language */
            language?: ("en" | "te") | null;
            /** Notification Mode */
            notification_mode?: string | null;
            /** Residence Country */
            residence_country?: string | null;
            /** Residence Region */
            residence_region?: string | null;
            /** Topic Slugs */
            topic_slugs?: string[] | null;
        };
        /** ProfileOut */
        ProfileOut: {
            /** Home City */
            home_city?: string | null;
            /** Home State */
            home_state?: string | null;
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "te";
            /** Notification Mode */
            notification_mode?: string | null;
            /** Residence Country */
            residence_country?: string | null;
            /** Residence Region */
            residence_region?: string | null;
            /** Topics */
            topics?: components["schemas"]["TopicOut"][];
        };
        /** PushTokenCreate */
        PushTokenCreate: {
            /**
             * Platform
             * @enum {string}
             */
            platform: "ios" | "android" | "web";
            /** Token */
            token: string;
        };
        /** PushTokenResponse */
        PushTokenResponse: {
            /** Registered */
            registered: boolean;
        };
        /** ReviewQueueItemOut */
        ReviewQueueItemOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decision */
            decision?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "IN_REVIEW" | "APPROVED" | "REJECTED";
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
        };
        /**
         * RightsEvidence
         * @description §5.1 evidence record beyond the first-class rights_evidence_url/
         *     rights_reviewed_at/reviewer columns on `AdminSourceOut`.
         */
        RightsEvidence: {
            /** Expires At */
            expires_at?: string | null;
            /** Notes */
            notes?: string | null;
            /** Permitted Fields */
            permitted_fields?: string[];
            /** Restrictions */
            restrictions?: string | null;
            /** Terms Url */
            terms_url?: string | null;
            /** Territory */
            territory?: string | null;
        };
        /** SavedStoryResponse */
        SavedStoryResponse: {
            /** Saved */
            saved: boolean;
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Items */
            items?: components["schemas"]["StoryOut"][];
            /** Query */
            query: string;
        };
        /** ShareMetaResponse */
        ShareMetaResponse: {
            /** Canonical Url */
            canonical_url: string;
            /** Description */
            description: string;
            /** Image Url */
            image_url?: string | null;
            /** Title */
            title: string;
        };
        /** StoriesListResponse */
        StoriesListResponse: {
            /** Items */
            items: components["schemas"]["StoryOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * StoryOut
         * @description Appendix A's sample content object, shaped for API consumption.
         */
        StoryOut: {
            /** Canonical Slug */
            canonical_slug: string;
            /** Countries */
            countries?: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Importance */
            importance: number;
            /** Published At */
            published_at?: string | null;
            /**
             * Sensitivity
             * @enum {string}
             */
            sensitivity: "NONE" | "IMMIGRATION" | "LEGAL" | "FINANCIAL" | "BREAKING" | "OBITUARY_ACCUSATION";
            /** Sources */
            sources?: components["schemas"]["StorySourceOut"][];
            /**
             * Status
             * @enum {string}
             */
            status: "DRAFT" | "AI_READY" | "REVIEW_REQUIRED" | "APPROVED" | "SCHEDULED" | "PUBLISHED" | "UPDATED" | "RETRACTED" | "CORRECTION_PENDING";
            /** Topics */
            topics?: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Variants */
            variants?: {
                [key: string]: components["schemas"]["StoryVariantOut"];
            };
        };
        /** StorySourceOut */
        StorySourceOut: {
            /** Published At */
            published_at?: string | null;
            /** Title */
            title?: string | null;
            /** Url */
            url: string;
        };
        /** StoryVariantOut */
        StoryVariantOut: {
            /** Headline */
            headline: string;
            /**
             * Language
             * @enum {string}
             */
            language: "en" | "te";
            /**
             * Qa Status
             * @default PENDING
             * @enum {string}
             */
            qa_status: "PENDING" | "PASSED" | "FAILED";
            /** Summary */
            summary: string;
            /** Why Matters */
            why_matters?: string | null;
        };
        /** TopicDetailResponse */
        TopicDetailResponse: {
            /** Stories */
            stories?: components["schemas"]["StoryOut"][];
            topic: components["schemas"]["TopicOut"];
        };
        /** TopicOut */
        TopicOut: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_audit_events_v1_admin_audit_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuditEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_admin_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_v1_admin_jobs_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kill_switches_v1_admin_kill_switches_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KillSwitchesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_queue_v1_admin_review_queue_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueueItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_v1_admin_sources_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSourceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_source_v1_admin_sources_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_source_v1_admin_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSourceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_story_v1_admin_stories__story_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_story_v1_admin_stories__story_id__correct_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_story_v1_admin_stories__story_id__reject_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retract_story_v1_admin_stories__story_id__retract_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    get_home_v1_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeResponse"];
                };
            };
        };
    };
    get_me_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_v1_me_account_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteAccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_preferences_v1_me_preferences_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_push_token_v1_me_push_tokens_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushTokenCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_story_v1_me_saved__story_id__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedStoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsave_story_v1_me_saved__story_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedStoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_v1_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stories_v1_stories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoriesListResponse"];
                };
            };
        };
    };
    get_story_v1_stories__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_story_share_meta_v1_stories__slug__share_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareMetaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topic_v1_topics__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
